---
- hosts: all

  become: true
  tasks:
        
    - name: Install neofetch
      apt:
        name: neofetch
        state: latest
        
    - name: Install crowdsec
      apt:
        name: crowdsec
        state: latest
