---
- hosts: all
  gather_facts: false
  become: true
  vars:
    packages_list:
      - snapd

    snap_paths:
      - /snap
      - /var/snap
      - /var/lib/snapd 
      - /var/cache/snapd 
      - /usr/lib/snapd 
      - /root/snap 
      - ~/snap
      
  tasks:
    - name: Stop and disable services from list
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false

      loop: "{{ packages_list }}"
        
    - name: Remove and purge packages from list
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        purge: true
      ignore_errors: yes

        
      loop: "{{ packages_list }}"

    - name: Delete content & directory (For snapd)
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"

      loop: "{{ snap_paths }}"
