---
- hosts: all
  gather_facts: false
  become: true
  vars:
    stop_services:
      - snapd.service
      
  tasks:
    #- service_facts:
    - name: stop and disable services from list
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      #when: "item in service_names"
      loop: "{{ stop_services }}"
      #vars:
      #  service_names: "{{ services|dict2items|map(attribute='value.name')|list }}"

    - name: Remove "snapd" package
      ansible.builtin.apt:
        name: "{{ stop_services }}"
        state: absent
        purge: true
