---
- hosts: all

  become: true
  tasks:

    - name: Disable SSHd root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: restart sshd

    - name: Disable SSHd password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
      notify: restart sshd
      
    - name: Set SSHd AuthenticationMethods
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: 'AuthenticationMethods publickey'
      notify: restart sshd
    
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
