---
- hosts: all

  become: true
  tasks:
    - name: Update SSH config to disable root login
      ini_file:
        path: /etc/ssh/ssh_config
        section: 'ssh'
        option: PermitRootLogin
        value: no
      notify: restart ssh

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
